name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: configure
      run: |
        chmod +x ./configure
        ./configure

    - name: make
      run: make

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zlib-1.1.4-build
        # Маска для поиска всех скомпилированных библиотек zlib
        path: |
          *.so*
          *.a
          libz.*
        if-no-files-found: warn
        retention-days: 14
        compression-level: 6
        overwrite: true
