name: Arch Linux Package Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: configure
      run: |
        chmod +x ./configure
        ./configure --shared

    - name: make
      run: make

    # Этот шаг превращает скомпилированные файлы в родной установщик .pkg.tar.zst
    # Используем утилиту makepkg внутри легковесного docker-контейнера Arch Linux
    - name: Build Arch Package (.pkg.tar.zst)
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest bash -c "
          pacman -Syu --noconfirm base-devel binutils &&
          useradd -m builder &&
          chown -R builder:builder /workspace &&
          sudo -u builder makepkg --nodeps --noprepare
        "

    - name: Upload Arch Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: arch-zlib-installer
        # Робот загрузит именно готовый скомпилированный установщик Arch
        path: "*.pkg.tar.zst"
        if-no-files-found: error
        retention-days: 7
